export const job_opt = [
    { value: 'flood', label: 'flood' },
    { value: 'fire', label: 'fire' },
    { value: 'mold', label: 'mold' },
    { value: 'abatement', label: 'abatement' },
    { value: 'packout', label: 'packout' },
];
export const email_opt = [
    { value: 'Receive invoice by admin', label: 'Receive invoice by admin' },
    { value: 'Add invoice by client', label: 'Add invoice by client' },
    { value: 'Need more photos', label: 'Need more photos' },
    { value: 'Need more documents', label: 'Need more documents' },
    { value: 'Invoice Ready/Make Payment', label: 'Invoice Ready/Make Payment' },
    { value: 'Completed', label: 'Completed' },
];
export const states_opt = [
    { value: "AK - Alaska", label: "AK - Alaska" },
    { value: "AL - Alabama", label: "AL - Alabama" },
    { value: "AR - Arkansas", label: "AR - Arkansas" },
    { value: "AS - American Samoa", label: "AS - American Samoa" },
    { value: "AZ - Arizona", label: "AZ - Arizona" },
    { value: "CA - California", label: "CA - California" },
    { value: "CO - Colorado", label: "CO - Colorado" },
    { value: "CT - Connecticut", label: "CT - Connecticut" },
    { value: "DC - District of Columbia", label: "DC - District of Columbia" },
    { value: "DE - Delaware", label: "DE - Delaware" },
    { value: "FL - Florida", label: "FL - Florida" },
    { value: "GA - Georgia", label: "GA - Georgia" },
    { value: "GU - Guam", label: "GU - Guam" },
    { value: "HI - Hawaii", label: "HI - Hawaii" },
    { value: "IA - Iowa", label: "IA - Iowa" },
    { value: "ID - Idaho", label: "ID - Idaho" },
    { value: "IL - Illinois", label: "IL - Illinois" },
    { value: "IN - Indiana", label: "IN - Indiana" },
    { value: "KS - Kansas", label: "KS - Kansas" },
    { value: "KY - Kentucky", label: "KY - Kentucky" },
    { value: "LA - Louisiana", label: "LA - Louisiana" },
    { value: "MA - Massachusetts", label: "MA - Massachusetts" },
    { value: "MD - Maryland", label: "MD - Maryland" },
    { value: "ME - Maine", label: "ME - Maine" },
    { value: "MI - Michigan", label: "MI - Michigan" },
    { value: "MN - Minnesota", label: "MN - Minnesota" },
    { value: "MO - Missouri", label: "MO - Missouri" },
    { value: "MS - Mississippi", label: "MS - Mississippi" },
    { value: "MT - Montana", label: "MT - Montana" },
    { value: "NC - North Carolina", label: "NC - North Carolina" },
    { value: "ND - North Dakota", label: "ND - North Dakota" },
    { value: "NE - Nebraska", label: "NE - Nebraska" },
    { value: "NH - New Hampshire", label: "NH - New Hampshire" },
    { value: "NJ - New Jersey", label: "NJ - New Jersey" },
    { value: "NM - New Mexico", label: "NM - New Mexico" },
    { value: "NV - Nevada", label: "NV - Nevada" },
    { value: "NY - New York", label: "NY - New York" },
    { value: "OH - Ohio", label: "OH - Ohio" },
    { value: "OK - Oklahoma", label: "OK - Oklahoma" },
    { value: "OR - Oregon", label: "OR - Oregon" },
    { value: "PA - Pennsylvania", label: "PA - Pennsylvania" },
    { value: "PR - Puerto Rico", label: "PR - Puerto Rico" },
    { value: "RI - Rhode Island", label: "RI - Rhode Island" },
    { value: "SC - South Carolina", label: "SC - South Carolina" },
    { value: "SD - South Dakota", label: "SD - South Dakota" },
    { value: "TN - Tennessee", label: "TN - Tennessee" },
    { value: "TX - Texas", label: "TX - Texas" },
    { value: "UT - Utah", label: "UT - Utah" },
    { value: "VA - Virginia", label: "VA - Virginia" },
    { value: "VI - Virgin Islands", label: "VI - Virgin Islands" },
    { value: "VT - Vermont", label: "VT - Vermont" },
    { value: "WA - Washington", label: "WA - Washington" },
    { value: "WI - Wisconsin", label: "WI - Wisconsin" },
    { value: "WV - West Virginia", label: "WV - West Virginia" },
    { value: "WY - Wyoming", label: "WY - Wyoming" },
]

export const status_opt = [
    { value: 'Pending', label: 'Pending' },
    { value: 'Need more photos', label: 'Need more photos' },
    { value: 'Need more documents', label: 'Need more documents' },
    { value: 'Invoice Ready/Make Payment', label: 'Invoice Ready/Make Payment' },
    { value: 'Completed', label: 'Completed' },
    { value: 'Other', label: 'Other' },
];
export const status_filter_opt = [
    { value: 'Pending', label: 'Pending' },
    { value: 'PhotoDoc', label: 'Needs More Documents/Needs More Photos' },
    { value: 'Redy', label: 'Invoice Ready/Make Payment' },
    { value: 'Other', label: 'Others' },
];

export const issuerImages = {
    visa: {
        src: require("../../../assets/visa.png"),
        className: "me-1",
        width: "30px",
        height: "30px",
    },
    mastercard: {
        src: require("../../../assets/mastercard.png"),
        className: "me-1",
        width: "30px",
        height: "30px",
    },
    amex: {
        src: require("../../../assets/amex.png"),
        className: "",
        width: "40px",
        height: "30px",
    },
    hipercard: {
        src: require("../../../assets/hipercard.png"),
        className: "me-2",
        width: "40px",
        height: "30px",
    },
    unionpay: {
        src: require("../../../assets/unionpay.png"),
        className: "me-1",
        width: "40px",
        height: "30px",
    },
    elo: {
        src: require("../../../assets/elo.jpg"),
        className: "me-2",
        width: "30px",
        height: "30px",
    },
    discover: {
        src: require("../../../assets/discover.png"),
        className: "me-2",
        width: "40px",
        height: "30px",
    },
    dinersclub: {
        src: require("../../../assets/dinersclub.png"),
        className: "me-2",
        width: "40px",
        height: "30px",
    },
};