const express = require("express");
const router=express.Router();
const authController=require("../controller/AuthController");
const invoiceController=require("../controller/InvoiceController");
const activityController=require("../controller/ActivityController");
const jobTypeController=require("../controller/JobTypeController");
const paymentController=require("../controller/PaymentController");
const PaymentIntegratController=require("../controller/PaymentIntegratController");
const DashboardController=require("../controller/DashboardController");
const CardController=require("../controller/CardController");
const NotifyController=require("../controller/NotificationController");
const HistoryController=require("../controller/HistoryController");
const {verifyToken}=require("../validator/AuthValidator");
var apiPath='/api';  

router.post(`${apiPath}/login`,authController.login);
router.post(`${apiPath}/logout`,authController.logout);

router.post(`${apiPath}/admin/create-account`,verifyToken,authController.createAccount);
router.post(`${apiPath}/admin/create-team-account`,verifyToken,authController.createTeamAccount);
router.post(`${apiPath}/admin/update-team-account/:id/:old_email`,verifyToken,authController.updateTeamAccount);
router.post(`${apiPath}/admin/update-account/:id/:old_email`,verifyToken,authController.updateAccount);
router.post(`${apiPath}/admin/delete-account/:id`,verifyToken,authController.deleteAccount);
router.post(`${apiPath}/user/create-invoice`,verifyToken,invoiceController.createInvoice);
router.get(`${apiPath}/admin/get-account`,verifyToken,authController.getRoleUserList);
router.get(`${apiPath}/admin/get-team-account`,verifyToken,authController.getTeamList);
router.get(`${apiPath}/user/get-invoice/:id`,verifyToken,invoiceController.getInvoice);
router.get(`${apiPath}/admin/get-invoice/:state`,verifyToken,invoiceController.getInvoiceAdminList);
router.get(`${apiPath}/admin/get-invoice-completed`,verifyToken,invoiceController.getInvoiceAdminCompletedList);
router.post(`${apiPath}/user/delete-photo/:id`,verifyToken,invoiceController.deletePhoto);
router.post(`${apiPath}/user/delete-sheet/:id`,verifyToken,invoiceController.deleteDemoSheet);
router.post(`${apiPath}/user/delete-invoice/:id`,verifyToken,invoiceController.deleteInvoice);
router.post(`${apiPath}/user/update-invoice/:id/:old_email`,verifyToken,invoiceController.updateInvoice);
router.post(`${apiPath}/admin/update-invoice-status/:id`,verifyToken,invoiceController.updateInvoiceStatus);
router.get(`${apiPath}/user/get-invoice-need/:id`,verifyToken,invoiceController.getInvoiceNeed);
router.post(`${apiPath}/user/search-globle/:id`,verifyToken,invoiceController.searchGloble);
router.post(`${apiPath}/upload-photo`,invoiceController.uploadPhoto);
router.get(`${apiPath}/get-photo/:id`,invoiceController.getPhotosByInvoice);
router.post(`${apiPath}/upload-document`,invoiceController.uploadDocument);
router.get(`${apiPath}/get-document/:id`,invoiceController.getDocumentByInvoice);
router.post(`${apiPath}/admin/task-manage-default/:id`,invoiceController.updateTaskManageDefault);
router.post(`${apiPath}/admin/task-manage-file/:id`,invoiceController.updateTaskManageFile);
router.post(`${apiPath}/admin/task-manage-amount/:id`,invoiceController.updateTaskManageAmount);
router.post(`${apiPath}/user/add-message`,verifyToken,activityController.addMessage);
router.post(`${apiPath}/admin/add-message`,verifyToken,activityController.addMessage);    
router.get(`${apiPath}/user/get-message/:id`,verifyToken,activityController.getMessage);
router.get(`${apiPath}/admin/get-message/:id`,verifyToken,activityController.getMessage);
router.get(`${apiPath}/admin/get-users`,verifyToken,authController.getUsers);
router.post(`${apiPath}/admin/add-job-type`,verifyToken,jobTypeController.addJobType);
router.post(`${apiPath}/admin/update-job-type/:id`,verifyToken,jobTypeController.updateJobType);
router.post(`${apiPath}/admin/delete-job-type/:id`,verifyToken,jobTypeController.deleteJobType);
router.get(`${apiPath}/admin/get-job-type`,verifyToken,jobTypeController.getJobTypes);
router.get(`${apiPath}/admin/get-job-type-list`,verifyToken,jobTypeController.getJobTypeList);
router.get(`${apiPath}/user/get-job-type`,verifyToken,jobTypeController.getJobTypes);
router.post(`${apiPath}/admin/add-payment`,verifyToken,paymentController.addPayment);
router.post(`${apiPath}/admin/update-payment/:id`,verifyToken,paymentController.updatePayment);
router.post(`${apiPath}/admin/delete-payment/:id`,verifyToken,paymentController.deletePayment);
router.get(`${apiPath}/admin/get-payment`,verifyToken,paymentController.getPayments);
router.get(`${apiPath}/admin/get-payment-list`,verifyToken,paymentController.getPaymentList);
router.post(`${apiPath}/user/add-stripe-payment`,verifyToken,PaymentIntegratController.createPayment);
router.get(`${apiPath}/user/get-invoice-id/:id`,verifyToken,invoiceController.getInvoiceById);
router.get(`${apiPath}/user/get-invoice-reports/:id`,verifyToken,invoiceController.getInvoiceReports);
router.get(`${apiPath}/admin/get-orders/:id`,verifyToken,PaymentIntegratController.getOrders);
router.get('/payment/success/:id/:user_id/:session_id',PaymentIntegratController.SuccessPayment)
router.get(`${apiPath}/admin/get-invoice-id/:id`,verifyToken,invoiceController.getInvoiceById);
router.post(`${apiPath}/user/create-user-team`,verifyToken,authController.createUserTeamAccount);
router.post(`${apiPath}/user/update-user-team/:id/:old_email`,verifyToken,authController.updateUserTeamAccount);
router.post(`${apiPath}/user/delete-user-team/:id`,verifyToken,authController.deleteUserTeam);
router.get(`${apiPath}/user/get-user-team/:id`,verifyToken,authController.getUserTeamList);
router.post(`${apiPath}/user/add-card`,verifyToken,CardController.addCard);
router.post(`${apiPath}/user/update-card/:id`,verifyToken,CardController.updateCard);
router.post(`${apiPath}/user/delete-card/:id`,verifyToken,CardController.deleteCard);
router.get(`${apiPath}/user/get-user-card/:id`,verifyToken,CardController.getCardList);
router.get(`${apiPath}/user/get-user-bill/:id`,verifyToken,PaymentIntegratController.getpaymentHistory);  
router.get(`${apiPath}/user/get-pay-amount/:id`,verifyToken,PaymentIntegratController.getpaymentAmount);  
router.post(`${apiPath}/user/make-card-default/:id`,verifyToken,CardController.updateStatus);
router.get(`${apiPath}/user/get-user-cards/:id`,verifyToken,CardController.getDatasUser);  
router.post(`${apiPath}/admin/make-payment-default/:id`,verifyToken,paymentController.updateStatus);
router.post(`${apiPath}/admin/update-notify/:id`,verifyToken,NotifyController.updateNotify);
router.get(`${apiPath}/admin/get-notify-admin`,verifyToken,NotifyController.getNotifysAdmin); 
router.post(`${apiPath}/user/update-notify/:id`,verifyToken,NotifyController.updateNotify);
router.post(`${apiPath}/user/add-notify`,verifyToken,NotifyController.addNotify);
router.post(`${apiPath}/admin/add-notify`,verifyToken,NotifyController.addNotify);
router.post(`${apiPath}/admin/delete-notify/:id`,verifyToken,NotifyController.deleteNotify);
router.get(`${apiPath}/user/get-notify-user/:id`,verifyToken,NotifyController.getNotifysUser); 
router.get(`${apiPath}/user/get-history/:id`,verifyToken,HistoryController.getHistory); 
router.get(`${apiPath}/user/get-history-list/:id`,verifyToken,HistoryController.getHistoryList); 
router.post(`${apiPath}/user/delete-history/:id`,verifyToken,HistoryController.deleteHistory);       
router.post(`${apiPath}/user/delete-history-all/:id`,verifyToken,HistoryController.deleteHistoryAll);   
router.post(`${apiPath}/admin/remaind-email`,verifyToken,NotifyController.remainderEmail);   
router.get(`${apiPath}/get-photos/:id`,invoiceController.getPhotos);    
router.get(`${apiPath}/get-documents/:id`,invoiceController.getDocuments);       
     
router.get(`${apiPath}/admin/get-completed-invoice-length`,verifyToken,DashboardController.getInvoiceCompletedAll);
router.get(`${apiPath}/admin/get-pending-invoice-length`,verifyToken,DashboardController.getInvoicePendingAll);
router.get(`${apiPath}/admin/get-needphotodoc-invoice-length`,verifyToken,DashboardController.getInvoiceNeedPhotosDocAll);
router.get(`${apiPath}/admin/get-neetdoc-invoice-length`,verifyToken,DashboardController.getInvoiceNeedDocumentsAll);
router.get(`${apiPath}/admin/get-redy-invoice-length`,verifyToken,DashboardController.getInvoiceReadyAll);
router.get(`${apiPath}/admin/get-order-length`,verifyToken,DashboardController.getOrdersAll);
router.get(`${apiPath}/admin/get-profit-length`,verifyToken,DashboardController.getProfitAll);
router.get(`${apiPath}/admin/get-job-length`,verifyToken,DashboardController.getJobTypeAll);
router.get(`${apiPath}/admin/get-stripAc-length`,verifyToken,DashboardController.getStripAccount);
router.get(`${apiPath}/admin/get-invoice-length`,verifyToken,DashboardController.getInvoicAll);
router.get(`${apiPath}/admin/get-user-length`,verifyToken,DashboardController.getUsersAll);
router.get(`${apiPath}/admin/get-other-invoice-length`,verifyToken,DashboardController.getInvoiceOtherAll);
router.get(`${apiPath}/admin/get-team-length`,verifyToken,DashboardController.getTeamAdmin);
router.get(`${apiPath}/admin/get-email-notification`,verifyToken,DashboardController.getNotification);

router.get("/", (req, res) => {         
    res.send("hello from the other sides")   
})                
module.exports = router;                       